version: '3.4'

services:
  hlservice.customer:
    environment:
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerTitle: "客户管理微服务组件"
      SwaggerDes: "客户信息管理服务"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "18080:8080"

  hlservice.identity:
    environment:
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerTitle: "身份认证微服务组件"
      SwaggerDes: "微服务集群身份认证与授权组件"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "18081:8080"

  hlservice.order:
    environment:
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerTitle: "订单微服务"
      SwaggerDes: "订单微服务组件"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "18082:8080"

  hlservice.product:
    environment:
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerTitle: "产品管理"
      SwaggerDes: "产品管理微服务组件"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "18083:8080"

  hlservice.schedule:
    environment:
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${SCHEDULE_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerTitle: "分布式任务调度组件"
      SwaggerDes: "任务调度微服务组件"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "18084:8080"

  hlservice.stock:
    environment:
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerTitle: "库存管理"
      SwaggerDes: "库存管理微服务组件"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "18085:8080"

  hlservice.systemmanager:
    environment:
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerTitle: "系统管理"
      SwaggerDes: "系统管理微服务组件"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "18086:8080"

  hlservice.wsserver:
    environment:
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${WS_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
    ports:
      - "196:96"